on:
  push:
    branches:
      - main

jobs:
  send-a-message:
    runs-on: ubuntu-latest
    steps:
      - name: send a test message
        run: |
          curl \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"content\":"test"}' \
            ${{ secrets.WEBHOOK }} \
