on:
  push:
    branches:
      - main

jobs:
  send-a-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          DIFF=$(git show --oneline -1 --unified=3 --color=never | head -c 1800)
          jq -n \
            --arg repo "${{ github.repository }}" \
            --arg sha "${{ github.sha }}" \
            --arg actor "${{ github.actor }}" \
            --arg msg "${{ github.event.head_commit.message }}" \
            --arg diff "$DIFF" \
            '{
              embeds: [{
                title: ("New push to " + $repo),
                description: ("**Commit:** [" + $sha + "](https://github.com/" + $repo + "/commit/" + $sha + ")\n**Author:** " + $actor + "\n**Message:** " + $msg),
                fields: [{ name: "Diff", value: ("```diff\n" + $diff + "\n```") }]
              }]
            }' > payload.json

          curl -X POST \
            -H "Content-Type: application/json" \
            -d @payload.json \
            "${{ secrets.WEBHOOK }}"
