on:
  push:
    branches:
      - main

jobs:
  send-a-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          DIFF="$(git show --oneline -1 --unified=3 --color=never | head -c 1500)"
          # keep only alphanumeric + newline + space
          DIFF_ESCAPED=$(printf "%s" "$DIFF" \
            | tr -cd '[:alnum:][:space:]' \
            | sed ':a;N;$!ba;s/\n/\\n/g')

          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
              \"embeds\": [{
                \"title\": \"New push to ${{ github.repository }}\",
                \"description\": \"Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }}\",
                \"fields\": [{
                  \"name\": \"Diff\",
                  \"value\": \"\`\`\`$DIFF_ESCAPED\`\`\`\"
                }]
              }]
            }" \
            "${{ secrets.WEBHOOK }}"
