on:
  push:
    branches:
      - main

jobs:
  send-a-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          DIFF=$(git show --oneline -1 --unified=3 --color=never | head -c 1800 | base64 -w0)

          echo '{
            "embeds": [{
              "title": "New push to '"${GITHUB_REPOSITORY}"'",
              "description": "**Commit:** ['"${GITHUB_SHA}"'](https://github.com/'"${GITHUB_REPOSITORY}"'/commit/'"${GITHUB_SHA}"')\n**Author:** '"${GITHUB_ACTOR}"'\n**Message:** '"${{ github.event.head_commit.message }}"'",
              "fields": [{
                "name": "Diff",
                "value": "```diff\n'$(echo "$DIFF" | base64 -d)'```"
              }]
            }]
          }' > payload.json

          curl -X POST \
            -H "Content-Type: application/json" \
            -d @payload.json \
            "${{ secrets.WEBHOOK }}"
