name: notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout thingy
        uses: actions/checkout@v4

      - name: send the message e
        run: |
          COMMIT_ID=$(git log -1 --pretty=format:"%H")
          AUTHOR=$(git log -1 --pretty=format:"%an")
          MESSAGE=$(git log -1 --pretty=format:"%s")
          PATCH=$(git show -1 --color=never --format= --unified=3 | head -c 1800)

          PAYLOAD=$(jq -n \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg commit "$COMMIT_ID" \
            --arg author "$AUTHOR" \
            --arg message "$MESSAGE" \
            --arg patch "$PATCH" \
            '{
              username: "updates i guess",
              embeds: [
                {
                  title: ("New push to " + $repo),
                  description: ("**Commit:** [" + $commit + "](https://github.com/" + $repo + "/commit/" + $commit + ")\n**Author:** " + $author + "\n**Message:** " + $message),
                  color: 7506394,
                  fields: [
                    {
                      name: "Diff",
                      value: ("```diff\n" + $patch + "\n```")
                    }
                  ],
                  url: "https://fly-ee.github.io/web_program/"
                }
              ]
            }')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               ${{ secrets.WEBHOOK }}
            # idk how workflows work, so i asked chatgpt
